# Generated by Django 6.0.5 on 2026-07-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('course', models.CharField(choices=[('free_discussion', 'Free Discussion'), ('a1_c1', 'دوره\u200cهای A1 تا C1'), ('toefl_course', 'دوره تخصصی تافل'), ('mock_toefl', 'ماک تافل')], max_length=30, verbose_name='دوره موردنظر')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('contacted', 'تماس گرفته شد'), ('completed', 'تکمیل شد'), ('cancelled', 'لغو شد')], default='new', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره',
                'verbose_name_plural': 'درخواست\u200cهای مشاوره',
                'ordering': ['-created_at'],
            },
        ),
    ]
