# Generated by Django 6.0.5 on 2026-07-05 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, help_text='General description shown before the mock starts.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MockAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('is_submitted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='toefl.mocktest')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Example: Module 1 or Module 2', max_length=255)),
                ('instructions', models.TextField(blank=True, help_text='Instructions shown at the beginning of this module.')),
                ('order', models.PositiveIntegerField(default=1, help_text='1 for Module 1, 2 for Module 2')),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_modules', to='toefl.mocktest')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReadingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('complete_words', 'Complete the Words'), ('notice', 'Notice'), ('email', 'Email'), ('text_message', 'Text Message'), ('daily_life', 'Daily Life Text'), ('academic_passage', 'Academic Passage'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(help_text='Example: Complete Words Text 1, Notice, Email, Passage 1', max_length=255)),
                ('instructions', models.TextField(blank=True, help_text='Instructions for this block.')),
                ('text', models.TextField(help_text='The paragraph, notice, email, message, or passage text.')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of this block inside the module.')),
                ('start_question_number', models.PositiveIntegerField(blank=True, help_text='Optional. Example: 1, 11, 21', null=True)),
                ('end_question_number', models.PositiveIntegerField(blank=True, help_text='Optional. Example: 10, 20, 22', null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='toefl.readingmodule')),
            ],
            options={
                'ordering': ['module__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('complete_word', 'Complete Word'), ('multiple_choice', 'Multiple Choice')], max_length=50)),
                ('question_number', models.PositiveIntegerField(help_text='Actual question number shown to the student. Example: 1, 2, 21')),
                ('question_text', models.TextField(blank=True, help_text='Question text. For complete words, this can be the incomplete word.')),
                ('incomplete_word', models.CharField(blank=True, help_text='For complete word questions. Example: environ____', max_length=255)),
                ('correct_answer', models.CharField(blank=True, help_text='For complete word questions. Example: environment', max_length=255)),
                ('order', models.PositiveIntegerField(default=1, help_text='Order inside the block.')),
                ('points', models.FloatField(default=1)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='toefl.readingblock')),
            ],
            options={
                'ordering': ['question_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReadingChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='toefl.readingquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.CharField(blank=True, help_text='Used for complete word questions.', max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='toefl.mockattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='toefl.readingquestion')),
                ('selected_choice', models.ForeignKey(blank=True, help_text='Used for multiple choice questions.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='toefl.readingchoice')),
            ],
            options={
                'ordering': ['question__question_number'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
