# Generated by Django 6.0.5 on 2026-07-06 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toefl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'ordering': ['global_question_number', 'question__question_number']},
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='readingquestion',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='readingquestion',
            name='incomplete_word',
        ),
        migrations.RemoveField(
            model_name='readingquestion',
            name='question_type',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='global_question_number',
            field=models.PositiveIntegerField(blank=True, help_text='Used for complete word questions where there is no ReadingQuestion object.', null=True),
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingblock',
            name='end_question_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='readingblock',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingblock',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='readingblock',
            name='start_question_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='readingblock',
            name='text',
            field=models.TextField(help_text='For Complete Words, use format: [correct_answer|incomplete_word]. Example: The development of agriculture was a [milestone|milest___] in history.'),
        ),
        migrations.AlterField(
            model_name='readingblock',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='readingmodule',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingmodule',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='readingmodule',
            name='title',
            field=models.CharField(help_text='Module 1 or Module 2', max_length=255),
        ),
        migrations.AlterField(
            model_name='readingquestion',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='readingquestion',
            name='question_number',
            field=models.PositiveIntegerField(help_text='Actual question number in the test.'),
        ),
        migrations.AlterField(
            model_name='readingquestion',
            name='question_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='toefl.readingquestion'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toefl.readingchoice'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='text_answer',
            field=models.CharField(blank=True, help_text="User's input for complete words.", max_length=255),
        ),
    ]
