# Generated by Django 6.0.5 on 2026-07-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toefl', '0002_alter_useranswer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingblock',
            name='text',
            field=models.TextField(help_text='Format: [fullword|startpart]'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='text_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
