# Generated by Django 6.0.5 on 2026-07-16 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toefl', '0003_alter_readingblock_text_alter_useranswer_text_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingmodule',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Module time limit in seconds. Example: 13:25 = 805'),
        ),
        migrations.CreateModel(
            name='ModuleAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_time_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_attempts', to='toefl.mockattempt')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_states', to='toefl.readingmodule')),
            ],
            options={
                'unique_together': {('attempt', 'module')},
            },
        ),
    ]
