# Generated by Django 6.0.5 on 2026-07-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toefl', '0004_readingmodule_time_limit_seconds_moduleattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingblock',
            name='email_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='readingblock',
            name='email_from',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='readingblock',
            name='email_subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='readingblock',
            name='email_to',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='readingblock',
            name='text',
            field=models.TextField(blank=True, help_text='General body text or complete-words format'),
        ),
    ]
