# Generated by Django 6.0.5 on 2026-07-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toefl', '0005_readingblock_email_date_readingblock_email_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingblock',
            name='email_date',
        ),
        migrations.RemoveField(
            model_name='readingblock',
            name='email_from',
        ),
        migrations.RemoveField(
            model_name='readingblock',
            name='email_subject',
        ),
        migrations.RemoveField(
            model_name='readingblock',
            name='email_to',
        ),
        migrations.AlterField(
            model_name='readingblock',
            name='text',
            field=models.TextField(help_text='Format: [fullword|startpart]'),
        ),
    ]
