# Generated by Django 6.0.5 on 2026-07-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toefl', '0006_remove_readingblock_email_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingblock',
            name='recipient',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='readingblock',
            name='sender',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='readingblock',
            name='sent_at_text',
            field=models.CharField(blank=True, help_text='Example: May 12, 10:30 AM', max_length=100),
        ),
        migrations.AddField(
            model_name='readingblock',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='readingblock',
            name='end_question_number',
            field=models.PositiveIntegerField(blank=True, help_text='Last question number of this block, optional.', null=True),
        ),
        migrations.AlterField(
            model_name='readingblock',
            name='start_question_number',
            field=models.PositiveIntegerField(blank=True, help_text='First question number of this block, used for complete_words.', null=True),
        ),
        migrations.AlterField(
            model_name='readingblock',
            name='text',
            field=models.TextField(help_text='For complete_words use format: [fullword|startpart]'),
        ),
    ]
