# Generated by Django 6.0.5 on 2026-07-18 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toefl', '0007_readingblock_recipient_readingblock_sender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('is_submitted', models.BooleanField(default=False)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_attempts', to='toefl.mocktest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Example: Writing Module 1', max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('time_limit_seconds', models.PositiveIntegerField(default=0, help_text='Time limit in seconds')),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_modules', to='toefl.mocktest')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WritingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('build_sentence', 'Build a Sentence / Fill in the Blanks')], default='build_sentence', max_length=50)),
                ('title', models.CharField(default='Make an appropriate sentence', max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('speaker_one_name', models.CharField(blank=True, max_length=100)),
                ('speaker_one_text', models.TextField(help_text='Example: Have you fixed your bicycle yet this week?')),
                ('speaker_two_name', models.CharField(blank=True, max_length=100)),
                ('answer_template', models.TextField(help_text='Use [blank] for every empty position. Example: Not really. [blank] [blank] I [blank].')),
                ('order', models.PositiveIntegerField(default=1)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='toefl.writingmodule')),
            ],
            options={
                'ordering': ['module__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WritingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_word_ids', models.JSONField(blank=True, default=list, help_text='Word IDs in the order selected by the user.')),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='toefl.writingattempt')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='toefl.writingblock')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt', 'block'), name='uniq_writing_answer')],
            },
        ),
        migrations.CreateModel(
            name='WritingWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='A word or phrase such as: the problem, is more serious', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=1, help_text='Position in the word bank')),
                ('correct_position', models.PositiveIntegerField(blank=True, help_text='Correct blank number: 1, 2, 3, etc. Leave empty if this word is a distractor.', null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='toefl.writingblock')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('block', 'correct_position'), name='uniq_writing_word_position')],
            },
        ),
    ]
