# Generated by Django 6.0.5 on 2026-07-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toefl', '0008_writingattempt_writingmodule_writingblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writinganswer',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='writinganswer',
            name='text_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='writinganswer',
            name='word_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='writingblock',
            name='email_recipient',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='writingblock',
            name='email_requirements',
            field=models.TextField(blank=True, help_text='Enter one requirement per line.'),
        ),
        migrations.AddField(
            model_name='writingblock',
            name='email_scenario',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='writingblock',
            name='email_subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='writingblock',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Time limit for this task in seconds. For Write an Email, use 420 seconds.'),
        ),
        migrations.AlterField(
            model_name='writingblock',
            name='answer_template',
            field=models.TextField(blank=True, help_text='Use [blank] for every empty position.'),
        ),
        migrations.AlterField(
            model_name='writingblock',
            name='block_type',
            field=models.CharField(choices=[('build_sentence', 'Build a Sentence / Fill in the Blanks'), ('write_email', 'Write an Email')], default='build_sentence', max_length=50),
        ),
        migrations.AlterField(
            model_name='writingblock',
            name='speaker_one_text',
            field=models.TextField(blank=True),
        ),
    ]
