# Generated by Django 6.0.5 on 2026-07-18 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toefl', '0009_writinganswer_is_graded_writinganswer_text_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingblock',
            name='discussion_class_title',
            field=models.CharField(blank=True, help_text='Example: School - Debate & Suggestions', max_length=255),
        ),
        migrations.AddField(
            model_name='writingblock',
            name='discussion_requirements',
            field=models.TextField(blank=True, help_text='Enter one requirement per line.'),
        ),
        migrations.AddField(
            model_name='writingblock',
            name='minimum_words',
            field=models.PositiveIntegerField(default=0, help_text='Recommended minimum word count. For this example use 100.'),
        ),
        migrations.AddField(
            model_name='writingblock',
            name='professor_avatar',
            field=models.CharField(blank=True, help_text='Optional image URL or static path. Example: /static/toefl/avatars/professor.png', max_length=500),
        ),
        migrations.AddField(
            model_name='writingblock',
            name='professor_name',
            field=models.CharField(blank=True, help_text='Example: Prof. Martin', max_length=100),
        ),
        migrations.AddField(
            model_name='writingblock',
            name='professor_prompt',
            field=models.TextField(blank=True, help_text="The professor's discussion question."),
        ),
        migrations.AlterField(
            model_name='writingblock',
            name='block_type',
            field=models.CharField(choices=[('build_sentence', 'Build a Sentence / Fill in the Blanks'), ('write_email', 'Write an Email'), ('academic_discussion', 'Write for an Academic Discussion')], default='build_sentence', max_length=50),
        ),
        migrations.CreateModel(
            name='AcademicDiscussionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Example: Alex', max_length=100)),
                ('avatar', models.CharField(blank=True, help_text='Optional image URL or static path. Example: /static/toefl/avatars/student1.png', max_length=500)),
                ('text', models.TextField(help_text="The student's response to the professor.")),
                ('order', models.PositiveIntegerField(default=1)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_posts', to='toefl.writingblock')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
