# Generated by Django 6.0.5 on 2026-07-18 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toefl', '0010_writingblock_discussion_class_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('is_submitted', models.BooleanField(default=False)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_attempts', to='toefl.mocktest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ListeningModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('time_limit_seconds', models.PositiveIntegerField(default=0, help_text='Optional module time limit in seconds.')),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_modules', to='toefl.mocktest')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ListeningBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('choose_best_response', 'Choose the Best Response')], default='choose_best_response', max_length=50)),
                ('title', models.CharField(default='Choose the best response', max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('speaker_image', models.ImageField(blank=True, null=True, upload_to='toefl/listening/images/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='toefl/listening/audio/')),
                ('lock_questions_until_audio_ends', models.BooleanField(default=True)),
                ('time_limit_seconds', models.PositiveIntegerField(default=15, help_text='Example: 15')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='toefl.listeningmodule')),
            ],
            options={
                'ordering': ['module__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(default=1)),
                ('question_text', models.TextField(blank=True, help_text='For this first type, you can leave it blank.')),
                ('order', models.PositiveIntegerField(default=1)),
                ('points', models.FloatField(default=1)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='toefl.listeningblock')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ListeningChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='toefl.listeningquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ListeningAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='toefl.listeningattempt')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toefl.listeningchoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='toefl.listeningquestion')),
            ],
            options={
                'ordering': ['question__order', 'id'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
