# Generated by Django 6.0.5 on 2026-07-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toefl', '0011_listeningattempt_listeningmodule_listeningblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningblock',
            name='hide_questions_until_audio_ends',
            field=models.BooleanField(default=False, help_text='When selected, the questions are completely hidden while the audio is playing. Use this for Conversation, Announcement, and Talk blocks.'),
        ),
        migrations.AddField(
            model_name='listeningblock',
            name='listening_content_type',
            field=models.CharField(blank=True, choices=[('conversation', 'Conversation'), ('announcement', 'Announcement'), ('talk', 'Talk')], default='', help_text='Select Conversation, Announcement, or Talk for Listen and Answer blocks.', max_length=30),
        ),
        migrations.AlterField(
            model_name='listeningblock',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Upload the audio file for this listening block.', null=True, upload_to='toefl/listening/audio/'),
        ),
        migrations.AlterField(
            model_name='listeningblock',
            name='block_type',
            field=models.CharField(choices=[('choose_best_response', 'Choose the Best Response'), ('listen_and_answer', 'Listen and Answer Questions')], default='choose_best_response', max_length=50),
        ),
        migrations.AlterField(
            model_name='listeningblock',
            name='lock_questions_until_audio_ends',
            field=models.BooleanField(default=True, help_text='Prevent the user from answering before the audio finishes.'),
        ),
        migrations.AlterField(
            model_name='listeningblock',
            name='speaker_image',
            field=models.ImageField(blank=True, help_text='Optional image shown beside the question or while the audio is playing.', null=True, upload_to='toefl/listening/images/'),
        ),
        migrations.AlterField(
            model_name='listeningblock',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(default=15, help_text='Time available for answering after or during the task. Example: 15 seconds.'),
        ),
    ]
