# Generated by Django 6.0.5 on 2026-07-19 16:23

import django.db.models.deletion
import toefl.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toefl', '0012_listeningblock_hide_questions_until_audio_ends_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('completed_questions', models.PositiveIntegerField(default=0)),
                ('is_submitted', models.BooleanField(default=False)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_attempts', to='toefl.mocktest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Example: Speaking Module 1', max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_modules', to='toefl.mocktest')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('listen_and_repeat', 'Listen and Repeat')], default='listen_and_repeat', max_length=50)),
                ('title', models.CharField(default='Listen and repeat only once.', max_length=255)),
                ('instructions', models.TextField(blank=True, help_text='Optional additional instructions shown to the student.')),
                ('order', models.PositiveIntegerField(default=1)),
                ('prompt_image', models.ImageField(blank=True, help_text='The image displayed while the user listens and records the response.', null=True, upload_to='toefl/speaking/images/')),
                ('prompt_audio', models.FileField(blank=True, help_text='The sentence audio that the user must listen to and repeat.', null=True, upload_to='toefl/speaking/prompts/')),
                ('reference_text', models.TextField(blank=True, help_text='Transcript of the audio or expected response. This is not shown to the student.')),
                ('preparation_time_seconds', models.PositiveSmallIntegerField(default=0, help_text='Optional delay between the end of the prompt and the start of recording.')),
                ('response_time_seconds', models.PositiveSmallIntegerField(default=8, help_text='Maximum recording time in seconds. Example: 8.')),
                ('play_prompt_once', models.BooleanField(default=True, help_text='Prevent the prompt audio from being replayed.')),
                ('auto_start_recording', models.BooleanField(default=True, help_text='Automatically start recording after the prompt audio finishes.')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='toefl.speakingmodule')),
            ],
            options={
                'ordering': ['module__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_audio', models.FileField(blank=True, null=True, upload_to=toefl.models.speaking_response_upload_to)),
                ('duration_seconds', models.FloatField(default=0, help_text="Actual duration of the user's recording.")),
                ('mime_type', models.CharField(blank=True, help_text='Example: audio/webm or audio/mp4.', max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_graded', models.BooleanField(default=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='toefl.speakingattempt')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='toefl.speakingblock')),
            ],
            options={
                'ordering': ['block__module__order', 'block__order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'block'), name='unique_speaking_answer_per_block')],
            },
        ),
    ]
