# Generated by Django 6.0.5 on 2026-07-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toefl', '0013_speakingattempt_speakingmodule_speakingblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingblock',
            name='prompt_video',
            field=models.FileField(blank=True, help_text='Use this for Watch and Respond.', null=True, upload_to='toefl/speaking/videos/'),
        ),
        migrations.AlterField(
            model_name='speakingblock',
            name='auto_start_recording',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='speakingblock',
            name='block_type',
            field=models.CharField(choices=[('listen_and_repeat', 'Listen and Repeat'), ('watch_and_respond', 'Watch and Respond')], default='listen_and_repeat', max_length=50),
        ),
        migrations.AlterField(
            model_name='speakingblock',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='speakingblock',
            name='play_prompt_once',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='speakingblock',
            name='preparation_time_seconds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='speakingblock',
            name='prompt_audio',
            field=models.FileField(blank=True, help_text='Use this for Listen and Repeat.', null=True, upload_to='toefl/speaking/prompts/'),
        ),
        migrations.AlterField(
            model_name='speakingblock',
            name='prompt_image',
            field=models.ImageField(blank=True, null=True, upload_to='toefl/speaking/images/'),
        ),
        migrations.AlterField(
            model_name='speakingblock',
            name='reference_text',
            field=models.TextField(blank=True, help_text='Hidden transcript or grading reference. This is not shown to the student.'),
        ),
        migrations.AlterField(
            model_name='speakingblock',
            name='response_time_seconds',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='speakingblock',
            name='title',
            field=models.CharField(default='Speaking Task', max_length=255),
        ),
    ]
