# Generated by Django 6.0.5 on 2026-07-19 19:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toefl', '0014_speakingblock_prompt_video_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduleattempt',
            options={'ordering': ['module__order', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='moduleattempt',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='moduleattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moduleattempt',
            name='current_block_index',
            field=models.PositiveIntegerField(default=0, help_text='The currently displayed block inside the module.'),
        ),
        migrations.AddField(
            model_name='moduleattempt',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='The server-side deadline for this reading module.', null=True),
        ),
        migrations.AlterField(
            model_name='moduleattempt',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='toefl.readingmodule'),
        ),
        migrations.AlterField(
            model_name='moduleattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='moduleattempt',
            constraint=models.UniqueConstraint(fields=('attempt', 'module'), name='unique_reading_module_attempt'),
        ),
    ]
