# Generated by Django 6.0.5 on 2026-07-20 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toefl', '0015_alter_moduleattempt_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingModuleAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_time_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Server-side deadline for this Writing module.', null=True)),
                ('current_block_index', models.PositiveIntegerField(default=0, help_text='Currently displayed block inside the Writing module.')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_attempts', to='toefl.writingattempt')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='toefl.writingmodule')),
            ],
            options={
                'ordering': ['module__order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'module'), name='unique_writing_module_attempt')],
            },
        ),
    ]
