# Generated by Django 6.0.5 on 2026-07-20 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toefl', '0016_writingmoduleattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='writinganswer',
            name='selected_word_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='FullTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_section', models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing'), ('speaking', 'Speaking'), ('completed', 'Completed')], default='reading', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('listening_attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='full_test_run', to='toefl.listeningattempt')),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_attempts', to='toefl.mocktest')),
                ('reading_attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='full_test_run', to='toefl.mockattempt')),
                ('speaking_attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='full_test_run', to='toefl.speakingattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_toefl_attempts', to=settings.AUTH_USER_MODEL)),
                ('writing_attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='full_test_run', to='toefl.writingattempt')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_completed', False)), fields=('user', 'mock_test'), name='unique_active_full_toefl_attempt')],
            },
        ),
    ]
